# Generated by Django 3.1.2 on 2020-10-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201020_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
