# Generated by Django 3.1.2 on 2020-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201021_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('SPRT', 'Sports'), ('FD', 'Food'), ('TVL', 'Travel'), ('ENT', 'Entertainment')], default='TVL', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('DFT', 'Draft'), ('APV', 'Approved'), ('SMTD', 'Submitted'), ('PBSHD', 'Published')], default='DFT', max_length=255),
        ),
    ]
