# Generated by Django 3.1.2 on 2020-10-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201021_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('ENT', 'Entertainment'), ('FD', 'Food'), ('SPRT', 'Sports'), ('TVL', 'Travel')], default='TVL', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('RJCT', 'Rejected'), ('APV', 'Approved'), ('SMTD', 'Submitted'), ('DFT', 'Draft'), ('PBSHD', 'Published')], default='DFT', max_length=255),
        ),
    ]
