# Generated by Django 3.1.2 on 2020-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20201023_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('ENT', 'Entertainment'), ('TVL', 'Travel'), ('SPRT', 'Sports'), ('FD', 'Food')], default='TVL', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('SMTD', 'Submitted'), ('DFT', 'Draft'), ('PBSHD', 'Published'), ('RJCT', 'Rejected'), ('APV', 'Approved')], default='DFT', max_length=255),
        ),
    ]
